version: '3'
services:
  web:
    build: .
    container_name: myweb
    image: myweb
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app --log-level=info --log-file=/dev/stdout
    volumes:
      - /home/ubuntu/logs:/logs
    working_dir: /app
    restart: always
  index_rss:
    container_name: index_rss
    image: myweb
    command: python task/new_index_rss.py
    working_dir: /app
    depends_on:
      - web
    restart: always
  download_icon:
    container_name: download_icon
    image: myweb
    command: python task/download_icon_redis_job.py
    working_dir: /app
    depends_on:
      - web
    volumes:
      - /home/ubuntu/data/static:/static
    restart: always
